import { NextRequest, NextResponse } from 'next/server'

function generatePineScript(strategy: any): string {
  const name = strategy.name || 'My Strategy'
  const riskPct = strategy.riskPct || 1
  const slPct = strategy.slPct || 2
  const tpPct = strategy.tpPct || 4

  const entryConds = (strategy.entryConds || []).map((c: any) => c.label || c.type || '').filter(Boolean)
  const exitConds = (strategy.exitConds || []).map((c: any) => c.label || c.type || '').filter(Boolean)

  return `//@version=6
strategy("${name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=${riskPct})

// ─── Inputs ───────────────────────────────────────────────
emaFastLen = input.int(9, "Fast EMA Length", minval=1)
emaSlowLen = input.int(21, "Slow EMA Length", minval=1)
ema200Len  = input.int(200, "Trend EMA Length", minval=1)
rsiLen     = input.int(14, "RSI Length", minval=1)
rsiOB      = input.float(70, "RSI Overbought", minval=50, maxval=100)
rsiOS      = input.float(30, "RSI Oversold",   minval=0,  maxval=50)
slPercent  = input.float(${slPct}, "Stop Loss %", minval=0.1, step=0.1)
tpPercent  = input.float(${tpPct}, "Take Profit %", minval=0.1, step=0.1)

// ─── Indicators ───────────────────────────────────────────
emaFast = ta.ema(close, emaFastLen)
emaSlow = ta.ema(close, emaSlowLen)
ema200  = ta.ema(close, ema200Len)
rsiVal  = ta.rsi(close, rsiLen)
vwapVal = ta.vwap(hlc3)

// ─── Entry Conditions ─────────────────────────────────────
// Strategy: ${name}
// Conditions: ${entryConds.join(', ') || 'EMA crossover'}
longCondition  = ta.crossover(emaFast, emaSlow) and close > ema200 and rsiVal > 50
shortCondition = ta.crossunder(emaFast, emaSlow) and close < ema200 and rsiVal < 50

// ─── Position Sizing ──────────────────────────────────────
longStop   = close * (1 - slPercent / 100)
longTarget = close * (1 + tpPercent / 100)
shortStop  = close * (1 + slPercent / 100)
shortTarget = close * (1 - tpPercent / 100)

// ─── Entries ──────────────────────────────────────────────
if longCondition
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=longStop, limit=longTarget)

if shortCondition
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=shortStop, limit=shortTarget)

// ─── Visuals ──────────────────────────────────────────────
plot(emaFast, "Fast EMA", color=color.blue, linewidth=1)
plot(emaSlow, "Slow EMA", color=color.orange, linewidth=1)
plot(ema200,  "EMA 200",  color=color.gray,   linewidth=2)
plotshape(longCondition,  "Buy",  shape.triangleup,   location.belowbar, color.green, size=size.small)
plotshape(shortCondition, "Sell", shape.triangledown,  location.abovebar, color.red,   size=size.small)
`
}

function generateNinjaScript(strategy: any): string {
  const name = (strategy.name || 'MyStrategy').replace(/[^a-zA-Z0-9]/g, '')
  const slPct = strategy.slPct || 2
  const tpPct = strategy.tpPct || 4

  return `// NinjaTrader 8 NinjaScript Strategy
// Strategy: ${strategy.name || 'My Strategy'}
// Generated by Nexyru

#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using NinjaTrader.Cbi;
using NinjaTrader.Gui;
using NinjaTrader.Gui.Chart;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.DrawingTools;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class ${name} : Strategy
    {
        private EMA emaFast;
        private EMA emaSlow;
        private EMA ema200;
        private RSI rsi;

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = "Generated by Nexyru - ${strategy.name}";
                Name = "${name}";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = true;
                StopTargetHandling = StopTargetHandling.PerEntryExecution;
            }
            else if (State == State.Configure)
            {
                emaFast = EMA(9);
                emaSlow = EMA(21);
                ema200  = EMA(200);
                rsi     = RSI(14, 3);

                SetStopLoss(CalculationMode.Percent, ${slPct});
                SetProfitTarget(CalculationMode.Percent, ${tpPct});
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < 200) return;

            // Long Entry
            bool longCondition = CrossAbove(emaFast, emaSlow, 1)
                && Close[0] > ema200[0]
                && rsi[0] > 50;

            // Short Entry
            bool shortCondition = CrossBelow(emaFast, emaSlow, 1)
                && Close[0] < ema200[0]
                && rsi[0] < 50;

            if (longCondition && Position.MarketPosition == MarketPosition.Flat)
            {
                EnterLong("Long Entry");
            }
            else if (shortCondition && Position.MarketPosition == MarketPosition.Flat)
            {
                EnterShort("Short Entry");
            }
        }
    }
}
`
}

function generatePython(strategy: any): string {
  const name = strategy.name || 'My Strategy'
  return `# Python Backtesting Script
# Strategy: ${name}
# Generated by Nexyru
# Requirements: pip install pandas numpy yfinance

import pandas as pd
import numpy as np
import yfinance as yf

# ─── Configuration ────────────────────────────────────────
SYMBOL = "ES=F"        # Change to your instrument
PERIOD = "1y"          # Data period
INTERVAL = "1h"        # Timeframe
EMA_FAST = 9
EMA_SLOW = 21
EMA_TREND = 200
RSI_LEN = 14
STOP_PCT = ${strategy.slPct || 2} / 100
TARGET_PCT = ${strategy.tpPct || 4} / 100
INITIAL_CAPITAL = 10000

# ─── Download Data ────────────────────────────────────────
print(f"Downloading {SYMBOL} data...")
df = yf.download(SYMBOL, period=PERIOD, interval=INTERVAL)
df.columns = df.columns.droplevel(1)

# ─── Indicators ───────────────────────────────────────────
df['ema_fast']  = df['Close'].ewm(span=EMA_FAST).mean()
df['ema_slow']  = df['Close'].ewm(span=EMA_SLOW).mean()
df['ema_trend'] = df['Close'].ewm(span=EMA_TREND).mean()

# RSI
delta = df['Close'].diff()
gain  = delta.where(delta > 0, 0).ewm(span=RSI_LEN).mean()
loss  = (-delta.where(delta < 0, 0)).ewm(span=RSI_LEN).mean()
df['rsi'] = 100 - (100 / (1 + gain / loss))

# ─── Signals ──────────────────────────────────────────────
df['long_signal']  = (
    (df['ema_fast'] > df['ema_slow']) &
    (df['ema_fast'].shift(1) <= df['ema_slow'].shift(1)) &
    (df['Close'] > df['ema_trend']) &
    (df['rsi'] > 50)
)
df['short_signal'] = (
    (df['ema_fast'] < df['ema_slow']) &
    (df['ema_fast'].shift(1) >= df['ema_slow'].shift(1)) &
    (df['Close'] < df['ema_trend']) &
    (df['rsi'] < 50)
)

# ─── Backtest ─────────────────────────────────────────────
capital   = INITIAL_CAPITAL
position  = 0
entry_price = 0
trades    = []

for i, row in df.iterrows():
    if position == 0:
        if row['long_signal']:
            position = 1
            entry_price = row['Close']
            stop  = entry_price * (1 - STOP_PCT)
            target = entry_price * (1 + TARGET_PCT)
    elif position == 1:
        if row['Close'] <= stop or row['Close'] >= target:
            pnl = (row['Close'] - entry_price) / entry_price
            capital *= (1 + pnl)
            trades.append({'entry': entry_price, 'exit': row['Close'], 'pnl': pnl})
            position = 0

# ─── Results ──────────────────────────────────────────────
if trades:
    results = pd.DataFrame(trades)
    wins = results[results['pnl'] > 0]
    losses = results[results['pnl'] < 0]

    print(f"\\n=== ${name} Backtest Results ===")
    print(f"Total Trades:     {len(trades)}")
    print(f"Win Rate:         {len(wins)/len(trades)*100:.1f}%")
    print(f"Total Return:     {(capital/INITIAL_CAPITAL-1)*100:.2f}%")
    print(f"Final Capital:    \${capital:,.2f}")
    print(f"Avg Win:          {wins['pnl'].mean()*100:.2f}%" if len(wins) > 0 else "Avg Win: N/A")
    print(f"Avg Loss:         {losses['pnl'].mean()*100:.2f}%" if len(losses) > 0 else "Avg Loss: N/A")
    profit_factor = abs(wins['pnl'].sum() / losses['pnl'].sum()) if len(losses) > 0 else float('inf')
    print(f"Profit Factor:    {profit_factor:.2f}")
else:
    print("No trades generated. Try adjusting parameters.")
`
}

export async function POST(req: NextRequest) {
  try {
    const { strategy, format } = await req.json()

    let code = ''
    if (format === 'pinescript') {
      code = generatePineScript(strategy)
    } else if (format === 'ninjatrader') {
      code = generateNinjaScript(strategy)
    } else if (format === 'python') {
      code = generatePython(strategy)
    } else {
      code = generatePineScript(strategy)
    }

    return NextResponse.json({ code })
  } catch(e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
